CREATE TABLE usuarios(
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil ENUM("ADMIN","USER") NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

